---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: huawei-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huawei-csi-controller
  template:
    metadata:
      labels:
        app: huawei-csi-controller
    spec:
      serviceAccount: huawei-csi-controller
      hostNetwork: true
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=6h"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/

        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.2.1
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/

        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v1.0.1
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/

        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v3.0.2
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir

        - name: snapshot-controller
          image: quay.io/k8scsi/snapshot-controller:v3.0.2
          args:
            - "--v=5"
            - "--leader-election=false"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir

        - name: huawei-csi-driver
          image: huawei-csi:*.*.*
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--controller"
            - "--containerized"
            - "--backend-update-interval=120"
            - "--driver-name=csi.huawei.com"
          env:
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: log
              mountPath: /var/log
            - name: config-map
              mountPath: /etc/huawei

      volumes:
        - name: socket-dir
          emptyDir:
        - name: log
          hostPath:
            path: /var/log/
            type: Directory
        - name: config-map
          configMap:
            name: huawei-csi-configmap
